### PR TITLE
Simplify annotation computations in RvsdgTreePrinter class

### PR DESCRIPTION
**Pull request by phate**
Use `std::count_if()` instead of explicit iteration to compute relevant annotations in `RvsdgTreePrinter` class.

### CODE REVIEW

**Review by phate — COMMENTED** [review]
I can not make use of the CountWhere() method for the structural inputs and outputs in the AnnotateNumMemoryStateInputsOutputs() method yet, as we do not have ranges for these yet.

**Comment by caleridas** [comment]
Would it not make more sense to defer to the std::count_if / std::ranges::count_if stdlib facilities?

**Comment by phate** [comment]
@caleridas I was not aware of them. Changed the PR. Thanks, I learned something!

**Review by haved — APPROVED** [review]
Looks good, nice use of the STL

**Pull request merged**
