### PR TITLE
Meta PR: Everything in adding Andersen alias analysis pass

### PR DESCRIPTION
**Pull request by haved**
This PR is being split up into sepratate PRs, see them instead

#297 Adds functionality for including named outputs in the GraphViz output of `PointsToGraphs`. *This PR is fully detached from the others*, only used for debugging.

Then there is  a chain of dependent PRs:
 - #298 Adds a class called `BiMap`, fast lookups in a bijective mapping using two `unordered_map`s.
 - #299 modified the `PointerObjectSet` to add function related constraints, and remove some unnecessary edges.
 - #300 adds the Andersen pass itself, and ports all tests from `TestSteensgaard`
 - #301 adds command line options to `jlm-opt`: `-AAAndersenRegionAware` and `-AAAndersenAgnostic`.

### CODE REVIEW

**Comment by haved** [comment]
I'm thinking change 3, the debug output modifications, can be removed from this PR and instead be added as a separate draft PR where we can discuss if there are better ways of making the output more useful, that don't involve passing in optional unordered maps between them.

**Comment by phate** [comment]
Could we split this huge PR up in smaller PRs such that this is easier to review and more digestible? My suggestion would be:
1. BiMap + tests (no dependency on anything)
2. PointerObjectSet Changes
3. rvsdg::view changes
4. Anderson (+ rest).

The smaller the PRs, the easier (and better) the review will be.

**Comment by phate** [comment]
All the split out PRs were merged. I guess we can close this PR now?

**Comment by haved** [comment]
Closing, as all PRs are merged

**Pull request closed without merging**
